name: go_wallet
description: "A modern mobile wallet tailored for Egyptian users to manage, save, and transfer money securely."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  easy_localization: ^3.0.8
  flutter_screenutil: ^5.9.3
  bloc: ^9.0.0
  firebase_core: ^4.0.0
  flutter_bloc: ^9.1.1
  lottie: ^3.3.1
  flutter_svg: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/lottie/
     - assets/svgs/



  fonts:
     - family: Zain
       fonts:
         - asset: assets/fonts/zain-bold.ttf
         - asset: assets/fonts/zain-regular.ttf



