name: go_wallet
description: "A modern mobile wallet tailored for Egyptian users to manage, save, and transfer money securely."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  easy_localization: ^3.0.8
  flutter_screenutil: ^5.9.3
  bloc: ^9.0.0
  firebase_core: ^4.0.0
  flutter_bloc: ^9.1.1
  lottie: ^3.3.1
  flutter_svg: ^2.0.13
  flutter_native_splash: ^2.4.6
  dots_indicator: ^4.0.1
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  another_flushbar: ^1.12.30
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  otp_pin_field: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
     - assets/lottie/
     - assets/svgs/
     - assets/images/
     - assets/translations/



  fonts:
     - family: Zain
       fonts:
         - asset: assets/fonts/zain-bold.ttf
         - asset: assets/fonts/zain-regular.ttf



